"""Add status column to caregiver table

Revision ID: 4cad6cdbba65
Revises: 94bd52b8b2d6
Create Date: 2024-09-08 12:54:51.066802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cad6cdbba65'
down_revision = '94bd52b8b2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_child',
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('caregiver_id', 'child_id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('child_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('financial', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('child_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    op.drop_table('caregiver_child')
    # ### end Alembic commands ###
