"""Add relationships

Revision ID: 94bd52b8b2d6
Revises: 
Create Date: 2024-09-08 08:54:39.305293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94bd52b8b2d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
