"""Create caregiver_child association table

Revision ID: 9bcb2a19067f
Revises: 8504e4d12407
Create Date: 2024-09-15 19:45:31.432579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bcb2a19067f'
down_revision = '8504e4d12407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_child',
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('caregiver_id', 'child_id')
    )
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.drop_table('caregiver_child')
    # ### end Alembic commands ###
